// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo0Hizi1ELS0W7NJ9zWeDNEMsQ3ofvUqo',
    appId: '1:120467884694:web:e6e8be7c23ddb8087a50b7',
    messagingSenderId: '120467884694',
    projectId: 'gdsc-skhu-coderoad',
    authDomain: 'gdsc-skhu-coderoad.firebaseapp.com',
    storageBucket: 'gdsc-skhu-coderoad.appspot.com',
    measurementId: 'G-TG081FR932',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1mab33QuXYFqL_TjOr6AIC1f_O8k8lu4',
    appId: '1:120467884694:android:aca2661108965bab7a50b7',
    messagingSenderId: '120467884694',
    projectId: 'gdsc-skhu-coderoad',
    storageBucket: 'gdsc-skhu-coderoad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLoZTIQplx1O30N8mfVnEgQBksTvfxitE',
    appId: '1:120467884694:ios:b926538ebface5547a50b7',
    messagingSenderId: '120467884694',
    projectId: 'gdsc-skhu-coderoad',
    storageBucket: 'gdsc-skhu-coderoad.appspot.com',
    iosClientId: '120467884694-03oiblesca8sgqgcgpblp5pmv2lq9k5a.apps.googleusercontent.com',
    iosBundleId: 'com.example.liferary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLoZTIQplx1O30N8mfVnEgQBksTvfxitE',
    appId: '1:120467884694:ios:b926538ebface5547a50b7',
    messagingSenderId: '120467884694',
    projectId: 'gdsc-skhu-coderoad',
    storageBucket: 'gdsc-skhu-coderoad.appspot.com',
    iosClientId: '120467884694-03oiblesca8sgqgcgpblp5pmv2lq9k5a.apps.googleusercontent.com',
    iosBundleId: 'com.example.liferary',
  );
}
